org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# Disable ART profile R8 rewriting to prevent compileReleaseArtProfile error
android.experimental.art-profile-r8-rewriting=false

# Disable Kotlin incremental compilation due to cross-drive (C: vs D:) path issues
kotlin.incremental=false
